# Generated by Django 2.2.5 on 2020-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_products_no_of_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.CharField(choices=[('Electronics & Office', 'Electronical & Office'), ('Cloth', 'Cloth'), ('Jewellery', 'Jewellery'), ('Games & Programs', 'Games & Programs'), ('Beauty & Health', 'Beauty & Health'), ('Automotives & Industrial', 'Automotives & Industrial'), ('Others', 'Others')], max_length=32, null=True),
        ),
    ]
