# Generated by Django 2.2.5 on 2020-05-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_status',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Slightly Used', 'Slightly Used')], max_length=32),
        ),
    ]
