# Generated by Django 2.2.5 on 2020-08-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200803_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
    ]
