# Generated by Django 2.2.12 on 2022-04-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200803_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='no_of_item',
            field=models.IntegerField(default=0),
        ),
    ]
