# Generated by Django 2.2.12 on 2022-04-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_products_no_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='tmp'),
        ),
    ]
