# Generated by Django 2.2.5 on 2020-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='location',
            field=models.CharField(choices=[('A.A', 'Addis Abeba'), ('HW', 'Hawassa'), ('B.D', 'Bahirdar'), ('D.D', 'Dire Dewa'), ('MK', 'Mekele'), ('JM', 'Jimma'), ('AS', 'Assosa'), ('HR', 'Harrar')], max_length=128),
        ),
    ]
